<a href="https://colab.research.google.com/github/Gautam12NI/102303739_UML_501_assignments/blob/main/102303739_Ass1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

# Q1 (a)
import numpy as np
arr = np.array([1,2,3,6,4,5])
rev = arr[::-1]
print("rev = ",rev)

rev =  [5 4 6 3 2 1]


In [4]:
# Q1 (b)
array1 = np.array([[1,2,3],[2,4,5],[1,2,3]])
flatt1 = array1.flatten()
print("arr = ",flatt1)
flatt2 = array1.ravel()
print("arr = ",flatt2)

arr =  [1 2 3 2 4 5 1 2 3]
arr =  [1 2 3 2 4 5 1 2 3]


In [3]:

# Q1 (c)
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])
np.array_equal(arr1,arr2)

True

In [2]:

# Q1 (d)
x = np.array([1,2,3,4,5,1,2,1,1,1])
val1 = int(np.bincount(x).argmax())
idx1 = np.where(x==val1)[0]
print("most freq ele in x is",val1,"on indices",idx1)

y = np.array([1,1,1,2,3,4,2,4,3,3])
val2 = int(np.bincount(y).argmax())
idx2 = np.where(y==val2)[0]
print("most freq ele in y is",val2, "on indices",idx2)

most freq ele in x is 1 on indices [0 5 7 8 9]
most freq ele in y is 1 on indices [0 1 2]


In [5]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

sum=gfg.sum()
print("Total sum:", sum)

rowsum=gfg.sum(axis=1)
print("Row-wise sum:\n", rowsum)

colsum=gfg.sum(axis=0)
print("Column-wise sum:\n",colsum )

Total sum: 45
Row-wise sum:
 [[14]
 [16]
 [15]]
Column-wise sum:
 [[20  9 16]]


In [6]:

# Q1 (f)
n_array = np.array([[55,25,15],[30,44,2],[11,45,77]])
diagsum = np.trace(n_array)
eigVals , eigVecs = np.linalg.eig(n_array)
inverse = np.linalg.inv(n_array)
det = np.linalg.det(n_array)
print("diagonal sum =",diagsum)
print("eigen values =",eigVals)
print("eigen vectors =",eigVecs)
print("inverse matrix =",inverse)
print("Determinant =",det)

diagonal sum = 176
eigen values = [98.16835147 28.097044   49.73460452]
eigen vectors = [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
inverse matrix = [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant = 137180.0000000001


In [7]:

# Q1 (g)
p1 = np.array([[1,2],[2,3]])
q1 = np.array([[4,5],[6,7]])

prod1 = np.dot(p1,q1)
cov1 = np.cov(p1.T,q1.T)

print("Product 1 =")
print(prod1)
print("\nCovariance 1 =")
print(cov1)

p2 = np.array([[1,2],[2,3],[4,5]])
q2 = np.array([[4,5,1],[6,7,2]])

prod2 = np.dot(p2,q2)
cov2 = np.cov(p2.T,q2)

print("\nProduct 2 =")
print(prod2)
print("\nCovariance 2 =")
print(cov2)

Product 1 =
[[16 19]
 [26 31]]

Covariance 1 =
[[0.5 0.5 1.  1. ]
 [0.5 0.5 1.  1. ]
 [1.  1.  2.  2. ]
 [1.  1.  2.  2. ]]

Product 2 =
[[16 19  5]
 [26 31  8]
 [46 55 14]]

Covariance 2 =
[[ 2.33333333  2.33333333 -2.66666667 -3.5       ]
 [ 2.33333333  2.33333333 -2.66666667 -3.5       ]
 [-2.66666667 -2.66666667  4.33333333  5.5       ]
 [-3.5        -3.5         5.5         7.        ]]


In [8]:
# Q1 (h)
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

inner = np.inner(x, y)
print("Inner product:")
print(inner)

outer = np.outer(x, y)
print("\nOuter product:")
print(outer)

a = x.flatten()
b = y.flatten()
cartesian = np.array([[i, j] for i in a for j in b])
print("\nCartesian product:")
print(cartesian)

Inner product:
[[17 52]
 [13 62]]

Outer product:
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]

Cartesian product:
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [9]:
# Q2 (a) i
array = np.array([[1,-2,3],[-4,5,-6]])
abs_array = np.abs(array)
print("Absolute values:")
print(abs_array)

Absolute values:
[[1 2 3]
 [4 5 6]]


In [10]:

# Q2 (a) ii

# Flattened array percentiles
x = array.flatten()
flat = np.percentile(x,[25,50,75])
print("\nPercentiles (flattened):")
print(flat)

# Column-wise percentiles
col = np.percentile(array,[25,50,75],axis=0)
print("\nPercentiles column-wise :")
print(col)

# Row-wise percentiles
row = np.percentile(array,[25, 50, 75],axis=1)
print("\nPercentiles row-wise :")
print(row)


Percentiles (flattened):
[-3.5 -0.5  2.5]

Percentiles column-wise :
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]

Percentiles row-wise :
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]


In [11]:
# Q2 (a) iii

# For entire array
mean = np.mean(array)
print("mean (all ele) :",mean)
median = np.median(array)
print("median (all ele) :",median)
std = np.std(array)
print("std (all ele) :",std)

# Column-wise
mean_col = np.mean(array, axis=0)
print("\n\nmean (col-wise)",mean_col)
median_col = np.median(array, axis=0)
print("median (col-wise)",median_col)
std_col = np.std(array, axis=0)
print("std (col-wise)",std_col)

# Row-wise
mean_row = np.mean(array, axis=1)
print("\n\nmean (row-wise)",mean_row)
median_row = np.median(array, axis=1)
print("median (row-wise)",median_row)
std_row = np.std(array, axis=1)
print("std (row-wise)",std_row)


mean (all ele) : -0.5
median (all ele) : -0.5
std (all ele) : 3.8622100754188224


mean (col-wise) [-1.5  1.5 -1.5]
median (col-wise) [-1.5  1.5 -1.5]
std (col-wise) [2.5 3.5 4.5]


mean (row-wise) [ 0.66666667 -1.66666667]
median (row-wise) [ 1. -4.]
std (row-wise) [2.05480467 4.78423336]


In [12]:
# Q2 (b)
a = np.array([-1.8,-1.6,-0.5,0.5,1.6,1.8,3.0])

floor = np.floor(a)
ceil = np.ceil(a)
trunc = np.trunc(a)
rounded = np.round(a)

print("Floor values:",floor)
print("\nCeiling values:",ceil)
print("\nTruncated values:",trunc)
print("\nRounded values:",rounded)

Floor values: [-2. -2. -1.  0.  1.  1.  3.]

Ceiling values: [-1. -1. -0.  1.  2.  2.  3.]

Truncated values: [-1. -1. -0.  0.  1.  1.  3.]

Rounded values: [-2. -2. -0.  0.  2.  2.  3.]


In [13]:
# Q3 (a)
array = np.array([10,52,62,16,16,54,453])

sortarr = np.sort(array)
print("Sorted array :",sortarr)
sortidx = np.argsort(array)
print("\nIndices of sorted array :", sortidx)
small_4 = sortarr[:4]
print("\n4 smallest elements :",small_4)
large_5 = sortarr[-5:]
print("\n5 largest elements :",large_5)

Sorted array : [ 10  16  16  52  54  62 453]

Indices of sorted array : [0 3 4 1 5 2 6]

4 smallest elements : [10 16 16 52]

5 largest elements : [ 16  52  54  62 453]


In [14]:
# Q3 (b)
array = np.array([1.0,1.2,2.2,2.0,3.0,2.0])

ints = array[array == array.astype(int)]
floats = array[array != array.astype(int)]

print("Integer elements only :",ints)
print("\nFloat elements only :",floats)

Integer elements only : [1. 2. 3. 2.]

Float elements only : [1.2 2.2]


In [33]:
# Q4(a)

from PIL import Image
import numpy as np

def img_to_array(path):
    img = Image.open(path)
    arr = np.array(img)

    if arr.ndim == 2:
        print("Grayscale image")
        np.savetxt("image_grayscale.txt", arr, fmt='%d')
        return "grayscale"
    else:
        print("RGB image")
        flat = arr.reshape(-1, arr.shape[2])
        np.savetxt("image_rgb.txt", flat, fmt='%d')
        return "rgb"

from google.colab import files
image_type = img_to_array("/content/Image")

RGB image


In [34]:

# Q4(b)

if image_type == "grayscale":
    gray = np.loadtxt("image_grayscale.txt", dtype=int)
    print("Grayscale image:")
    print(gray)

elif image_type == "rgb":
    rgb = np.loadtxt("image_rgb.txt", dtype=int)
    print("RGB image:")
    print(rgb)

else:
    print("Image not loaded")


RGB image:
[[ 65 117 186]
 [ 65 117 186]
 [ 65 117 186]
 ...
 [  0  96 159]
 [  0  96 159]
 [  0  96 159]]
