<a href="https://colab.research.google.com/github/Gautam12NI/102303739_UML_501_assignments/blob/main/NumPy_Assignment_Complete_Solution_(Direct).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from PIL import Image
import os

# Q1: Questions on Basic NumPy Array
print("--- Q1: Questions on Basic NumPy Array ---")

# (a)
print("\n--- (a) ---")
arr_a = np.array([1, 2, 3, 6, 4, 5])
reversed_arr_a = arr_a[::-1]
print(f"Original: {arr_a}")
print(f"Reversed: {reversed_arr_a}")

# (b)
print("\n--- (b) ---")
array1_b = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flattened_1 = array1_b.flatten()
flattened_2 = array1_b.ravel()
print(f"Original:\n{array1_b}")
print(f"Flattened (method 1): {flattened_1}")
print(f"Flattened (method 2): {flattened_2}")

# (c)
print("\n--- (c) ---")
arr1_c = np.array([[1, 2], [3, 4]])
arr2_c = np.array([[1, 2], [3, 4]])
comparison_result = np.array_equal(arr1_c, arr2_c)
print(f"arr1:\n{arr1_c}")
print(f"arr2:\n{arr2_c}")
print(f"Arrays are equal: {comparison_result}")

# (d)
print("\n--- (d) ---")
x_d = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y_d = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
most_frequent_x = np.bincount(x_d).argmax()
indices_x = np.where(x_d == most_frequent_x)[0]
most_frequent_y = np.bincount(y_d).argmax()
indices_y = np.where(y_d == most_frequent_y)[0]
print(f"Array x: {x_d}")
print(f"Most frequent value in x: {most_frequent_x}")
print(f"Indices of most frequent value in x: {indices_x}")
print(f"Array y: {y_d}")
print(f"Most frequent value in y: {most_frequent_y}")
print(f"Indices of most frequent value in y: {indices_y}")

# (e)
print("\n--- (e) ---")
gfg_e = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
sum_all = gfg_e.sum()
sum_row = gfg_e.sum(axis=1)
sum_col = gfg_e.sum(axis=0)
print(f"Matrix gfg:\n{gfg_e}")
print(f"Sum of all elements: {sum_all}")
print(f"Sum of all elements row-wise:\n{sum_row}")
print(f"Sum of all elements column-wise: {sum_col}")

# (f)
print("\n--- (f) ---")
n_array_f = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
diag_sum = np.trace(n_array_f)
eigen_values, eigen_vectors = np.linalg.eig(n_array_f)
inverse_matrix = np.linalg.inv(n_array_f)
determinant = np.linalg.det(n_array_f)
print(f"Matrix n_array:\n{n_array_f}")
print(f"Sum of diagonal elements: {diag_sum}")
print(f"Eigen values: {eigen_values}")
print(f"Eigen vectors:\n{eigen_vectors}")
print(f"Inverse of matrix:\n{inverse_matrix}")
print(f"Determinant of matrix: {determinant}")

# (g)
print("\n--- (g) ---")
p_g1 = np.array([[1, 2], [2, 3]])
q_g1 = np.array([[4, 5], [6, 7]])
product_g1 = np.dot(p_g1, q_g1)
covariance_g1 = np.cov(p_g1, q_g1)
print(f"Matrix p (i):\n{p_g1}")
print(f"Matrix q (i):\n{q_g1}")
print(f"Product (i):\n{product_g1}")
print(f"Covariance (i):\n{covariance_g1}")

p_g2 = np.array([[1, 2], [2, 3], [4, 5]])
q_g2 = np.array([[4, 5, 1], [6, 7, 2]])
product_g2 = np.dot(q_g2, p_g2)
# Covariance requires arrays of the same shape. Flatten them for a meaningful comparison.
covariance_g2 = np.cov(p_g2.flatten(), q_g2.flatten())
print(f"\nMatrix p (ii):\n{p_g2}")
print(f"Matrix q (ii):\n{q_g2}")
print(f"Product (ii):\n{product_g2}")
print(f"Covariance of flattened arrays (ii):\n{covariance_g2}")

# (h)
print("\n--- (h) ---")
x_h = np.array([[2, 3, 4], [3, 2, 9]])
y_h = np.array([[1, 5, 0], [5, 10, 3]])
inner_product = np.inner(x_h, y_h)
outer_product = np.outer(x_h, y_h)
# Cartesian product requires a helper function
def cartesian_product(*arrays):
    la = len(arrays)
    dtype = np.result_type(*arrays)
    arr = np.empty([len(a) for a in arrays] + [la], dtype=dtype)
    for i, a in enumerate(np.ix_(*arrays)):
        arr[..., i] = a
    return arr.reshape(-1, la)
cartesian_prod = cartesian_product(x_h.flatten(), y_h.flatten())
print(f"Matrix x:\n{x_h}")
print(f"Matrix y:\n{y_h}")
print(f"Inner product:\n{inner_product}")
print(f"Outer product:\n{outer_product}")
print(f"Cartesian product of flattened arrays:\n{cartesian_prod}")

# Q2: Based on NumPy Mathematics and Statistics
print("\n--- Q2: Based on NumPy Mathematics and Statistics ---")

# (a)
print("\n--- (a) ---")
array_a2 = np.array([[1, 2, 3], [-4, 5, -6]])
abs_val = np.abs(array_a2)
p_flat = np.percentile(array_a2, [25, 50, 75])
p_col = np.percentile(array_a2, [25, 50, 75], axis=0)
p_row = np.percentile(array_a2, [25, 50, 75], axis=1)
mean_flat = np.mean(array_a2)
median_flat = np.median(array_a2)
std_flat = np.std(array_a2)
mean_col = np.mean(array_a2, axis=0)
median_col = np.median(array_a2, axis=0)
std_col = np.std(array_a2, axis=0)
mean_row = np.mean(array_a2, axis=1)
median_row = np.median(array_a2, axis=1)
std_row = np.std(array_a2, axis=1)
print(f"Original array:\n{array_a2}")
print(f"Element-wise absolute value:\n{abs_val}")
print(f"25th, 50th, 75th percentile of flattened array: {p_flat}")
print(f"25th, 50th, 75th percentile of each column:\n{p_col}")
print(f"25th, 50th, 75th percentile of each row:\n{p_row}")
print(f"Mean, Median, Std of flattened array: {mean_flat}, {median_flat}, {std_flat}")
print(f"Mean of each column: {mean_col}")
print(f"Median of each column: {median_col}")
print(f"Std of each column: {std_col}")
print(f"Mean of each row: {mean_row}")
print(f"Median of each row: {median_row}")
print(f"Std of each row: {std_row}")

# (b)
print("\n--- (b) ---")
a_b2 = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
floor_val = np.floor(a_b2)
ceil_val = np.ceil(a_b2)
trunc_val = np.trunc(a_b2)
round_val = np.round(a_b2)
print(f"Original array: {a_b2}")
print(f"Floor values: {floor_val}")
print(f"Ceiling values: {ceil_val}")
print(f"Truncated values: {trunc_val}")
print(f"Rounded values: {round_val}")

# Q3: Based on Searching and Sorting
print("\n--- Q3: Based on Searching and Sorting ---")

# (a)
print("\n--- (a) ---")
array_a3 = np.array([10, 52, 62, 16, 16, 54, 453])
sorted_arr = np.sort(array_a3)
sorted_indices = np.argsort(array_a3)
four_smallest = sorted_arr[:4]
five_largest = sorted_arr[-5:]
print(f"Original array: {array_a3}")
print(f"Sorted array: {sorted_arr}")
print(f"Indices of sorted array: {sorted_indices}")
print(f"4 smallest elements: {four_smallest}")
print(f"5 largest elements: {five_largest}")

# (b)
print("\n--- (b) ---")
array_b3 = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
integers_only = array_b3[array_b3 == array_b3.astype(int)]
floats_only = array_b3[array_b3 != array_b3.astype(int)]
print(f"Original array: {array_b3}")
print(f"Integer elements only: {integers_only}")
print(f"Float elements only: {floats_only}")

# Q4: Based on Image Processing
print("\n--- Q4: Based on Image Processing ---")

# (a)
print("\n--- (a) ---")
def img_to_array(path, output_filename="image_data.txt"):
    try:
        img = Image.open(path)
        img_array = np.array(img)

        # Reshape for saving to text file
        if img_array.ndim == 3: # RGB
            reshaped_array = img_array.reshape(img_array.shape[0], -1)
        else: # Grayscale
            reshaped_array = img_array

        np.savetxt(output_filename, reshaped_array, fmt='%d')
        print(f"Image from '{path}' saved as array to '{output_filename}'")
        return img_array.shape # Return original shape for reloading
    except FileNotFoundError:
        print(f"Error: The file at '{path}' was not found.")
        return None

# Create a dummy image for demonstration
dummy_rgb_array = np.random.randint(0, 256, (10, 20, 3), dtype=np.uint8)
dummy_rgb_image = Image.fromarray(dummy_rgb_array)
dummy_rgb_path = "dummy_rgb.png"
dummy_rgb_image.save(dummy_rgb_path)

dummy_gray_array = np.random.randint(0, 256, (10, 20), dtype=np.uint8)
dummy_gray_image = Image.fromarray(dummy_gray_array)
dummy_gray_path = "dummy_gray.png"
dummy_gray_image.save(dummy_gray_path)

# Run the function
rgb_shape = img_to_array(dummy_rgb_path, "rgb_image_data.txt")
gray_shape = img_to_array(dummy_gray_path, "gray_image_data.txt")

# (b)
print("\n--- (b) ---")
def load_array_from_txt(filename, original_shape):
    if not os.path.exists(filename):
        print(f"File '{filename}' does not exist.")
        return None

    loaded_flat_array = np.loadtxt(filename, dtype=np.uint8)

    # Reshape back to original image dimensions
    if len(original_shape) == 3: # RGB
        loaded_array = loaded_flat_array.reshape(original_shape)
    else: # Grayscale
        loaded_array = loaded_flat_array

    print(f"Successfully loaded array from '{filename}'")
    return loaded_array

if rgb_shape:
    loaded_rgb_data = load_array_from_txt("rgb_image_data.txt", rgb_shape)
    if loaded_rgb_data is not None:
        print(f"Shape of loaded RGB data: {loaded_rgb_data.shape}")

if gray_shape:
    loaded_gray_data = load_array_from_txt("gray_image_data.txt", gray_shape)
    if loaded_gray_data is not None:
        print(f"Shape of loaded Grayscale data: {loaded_gray_data.shape}")

--- Q1: Questions on Basic NumPy Array ---

--- (a) ---
Original: [1 2 3 6 4 5]
Reversed: [5 4 6 3 2 1]

--- (b) ---
Original:
[[1 2 3]
 [2 4 5]
 [1 2 3]]
Flattened (method 1): [1 2 3 2 4 5 1 2 3]
Flattened (method 2): [1 2 3 2 4 5 1 2 3]

--- (c) ---
arr1:
[[1 2]
 [3 4]]
arr2:
[[1 2]
 [3 4]]
Arrays are equal: True

--- (d) ---
Array x: [1 2 3 4 5 1 2 1 1 1]
Most frequent value in x: 1
Indices of most frequent value in x: [0 5 7 8 9]
Array y: [1 1 1 2 3 4 2 4 3 3]
Most frequent value in y: 1
Indices of most frequent value in y: [0 1 2]

--- (e) ---
Matrix gfg:
[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]
Sum of all elements: 45
Sum of all elements row-wise:
[[14]
 [16]
 [15]]
Sum of all elements column-wise: [[20  9 16]]

--- (f) ---
Matrix n_array:
[[55 25 15]
 [30 44  2]
 [11 45 77]]
Sum of diagonal elements: 176
Eigen values: [98.16835147 28.097044   49.73460452]
Eigen vectors:
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034